import React, { useState, useEffect } from "react";
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import axios from 'axios';
export default function () {
    const [messages, setMessages] = useState(0)
    const getMessages = () => {
        axios.get(`https://jsonplaceholder.typicode.com/users`)
            .then(res => {
                const data = res.data
                setMessages({ data });
            })
    }
    useEffect(() => {
        getMessages();
    })
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                </div>
            </main>
        </div>
    )
}